# Generated by Django 5.2.7 on 2025-10-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0002_scammer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scammer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scammer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='scammer',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ScammerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='scammers.scammer')),
            ],
        ),
        migrations.CreateModel(
            name='ScammerPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='scammers.scammer')),
            ],
        ),
    ]
