# Generated by Django 5.2.7 on 2025-10-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0003_remove_scammer_name_remove_scammer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scammer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scammer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scammer',
            name='website',
        ),
        migrations.CreateModel(
            name='ScammerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='scammers.scammer')),
            ],
        ),
        migrations.CreateModel(
            name='ScammerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scammer_images/')),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scammers.scammer')),
            ],
        ),
        migrations.CreateModel(
            name='ScammerWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='scammers.scammer')),
            ],
        ),
    ]
