# Generated by Django 5.2.7 on 2025-10-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0004_remove_scammer_email_remove_scammer_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='scammer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='scammers.tag'),
        ),
    ]
