# Generated by Django 5.2.7 on 2025-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0005_tag_scammer_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scammer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scammeremail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='scammerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scammer_images/'),
        ),
        migrations.AlterField(
            model_name='scammername',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scammerphonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scammerwebsite',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
