# Generated by Django 5.2.7 on 2025-10-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0006_alter_scammer_description_alter_scammeremail_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scammer',
            name='custom_attributes',
        ),
    ]
