# Generated by Django 5.2.7 on 2025-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0007_remove_scammer_custom_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scammerphonenumber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
