# Generated by Django 5.2.7 on 2025-10-20 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0008_alter_scammerphonenumber_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScammerPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='scammers.scammer')),
            ],
        ),
    ]
