# Generated by Django 5.2.7 on 2025-10-20 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0009_scammerpaymentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScammerCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=255)),
                ('field_value', models.CharField(blank=True, max_length=255, null=True)),
                ('scammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='scammers.scammer')),
            ],
        ),
    ]
