# Generated by Django 5.2.7 on 2025-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0010_scammercustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
