# Generated by Django 5.2.7 on 2025-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0011_scammer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
