# Generated by Django 5.2.7 on 2025-10-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0013_userscammeraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('premium', 'Premium')], default='public', max_length=10)),
            ],
            options={
                'unique_together': {('model_name', 'field_name')},
            },
        ),
    ]
