# Generated by Django 5.2.7 on 2025-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0014_fieldaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='related_scammers',
            field=models.ManyToManyField(blank=True, to='scammers.scammer'),
        ),
    ]
