# Generated by Django 5.2.7 on 2025-10-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0015_scammer_related_scammers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScammerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cases', models.ManyToManyField(related_name='profiles', to='scammers.scammer')),
            ],
        ),
    ]
