# Generated by Django 5.2.7 on 2025-10-28 10:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0016_scammerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scammer',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scammerprofile',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
