# Generated by Django 5.2.7 on 2025-10-28 10:33

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('scammers', '0017_scammer_search_vector_scammerprofile_search_vector'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE INDEX scammers_scammer_search_vector_idx
            ON scammers_scammer
            USING GIN (search_vector);
            ''',
            '''
            DROP INDEX scammers_scammer_search_vector_idx;
            '''
        ),
        migrations.RunSQL(
            '''
            CREATE INDEX scammers_scammerprofile_search_vector_idx
            ON scammers_scammerprofile
            USING GIN (search_vector);
            ''',
            '''
            DROP INDEX scammers_scammerprofile_search_vector_idx;
            '''
        ),
    ]
